/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
import { InjectionToken } from "@angular/core";

/** Injection token for providing an API key. */
export const API_KEY_TOKEN = new InjectionToken<string>('API_KEY');
/** Injection token for providing a bearer token or a function that returns a bearer token. */
export const BEARER_TOKEN_TOKEN = new InjectionToken<string | (() => string)>('BEARER_TOKEN');
