/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import { Injectable } from "@angular/core";

/** A simple service to manage OAuth tokens stored in localStorage. */
@Injectable({ providedIn: 'root' })
export class OAuthService {
  private readonly TOKEN_KEY = 'oauth_token';

  setToken(token: string) {
    localStorage.setItem(this.TOKEN_KEY, token);
  }

  getToken(): string | null {
    return localStorage.getItem(this.TOKEN_KEY);
  }

  clearToken() {
    localStorage.removeItem(this.TOKEN_KEY);
  }
}
