/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import { EnvironmentProviders, makeEnvironmentProviders, Provider } from "@angular/core";
import { HTTP_INTERCEPTORS, HttpInterceptor } from "@angular/common/http";
import { BASE_PATH_DEFAULT, HTTP_INTERCEPTORS_DEFAULT } from "./tokens";
import { DefaultBaseInterceptor } from "./utils/base-interceptor";
import { DateInterceptor } from "./utils/date-transformer";
import { AuthInterceptor } from "./auth/auth.interceptor";
import { API_KEY_TOKEN, BEARER_TOKEN_TOKEN } from "./auth/auth.tokens";

/** Configuration for the Default API client. */
export interface DefaultConfig {
  /** The base path of the API endpoint (e.g., 'https://api.example.com/v1'). */
  basePath: string;
  /** If true, automatically transforms ISO date strings in responses to Date objects. Default: true */
  enableDateTransform?: boolean;
  /** An array of custom HttpInterceptor classes to apply to requests for this client. */
  interceptors?: (new (...args: any[]) => HttpInterceptor)[];
  /** The API key to be used for authentication. */
  apiKey?: string;
  /** The Bearer token or a function returning the token for authentication. */
  bearerToken?: string | (() => string);
}

/** Provides the necessary services and configuration for the Default API client. */
/** This function should be used in the `providers` array of your application's bootstrap logic or a feature module. */
/**
 * @example
 */
/** ```typescript */
/** bootstrapApplication(AppComponent, { */
/**   providers: [ */
/**     provideHttpClient(withInterceptorsFromDi()), */
/**     provideTestClient({ basePath: 'http://localhost:3000' }) */
/**   ] */
/** }); */
/** ``` */

/** @param config The client configuration object. */
/** @returns A set of providers to be included in your application's bootstrap logic. */
export function provideDefaultClient(config: DefaultConfig): EnvironmentProviders {
  const providers: Provider[] = [
    { provide: BASE_PATH_DEFAULT, useValue: config.basePath },
    // The base interceptor is responsible for applying all client-specific interceptors.
    { provide: HTTP_INTERCEPTORS, useClass: DefaultBaseInterceptor, multi: true }
  ];

  // Provide the AuthInterceptor to handle adding auth credentials to requests.
  providers.push({ provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true });

  if (config.apiKey) {
    providers.push({ provide: API_KEY_TOKEN, useValue: config.apiKey });
  }

  if (config.bearerToken) {
    providers.push({ provide: BEARER_TOKEN_TOKEN, useValue: config.bearerToken });
  }

  // Instantiate custom interceptors provided by the user.
  const customInterceptors = config.interceptors?.map(InterceptorClass => new InterceptorClass()) || [];

  if (config.enableDateTransform !== false) {
    // The date transformer interceptor runs before other custom interceptors.
    customInterceptors.unshift(new DateInterceptor());
  }

  // Provide a single array of all client-specific interceptors for the BaseInterceptor to use.
  providers.push({ provide: HTTP_INTERCEPTORS_DEFAULT, useValue: customInterceptors });

  return makeEnvironmentProviders(providers);
}
