/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import { Component, inject, OnInit } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { first } from "rxjs/operators";
import { OAuthService } from "../oauth.service";

/** Handles the redirect from an OAuth provider, extracting the access token from the URL fragment. */
@Component({
  selector: 'app-oauth-redirect',
  templateUrl: './oauth-redirect.component.html',
  standalone: true
})
export class OauthRedirectComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly oauthService = inject(OAuthService);

  ngOnInit() {
    this.route.fragment.pipe(first()).subscribe(fragment => {
      if (fragment) {
        const params = new URLSearchParams(fragment);
        const accessToken = params.get('access_token');
        if (accessToken) {
          this.oauthService.setToken(accessToken);
          this.router.navigate(['/']);
        } else {
          console.error('OAuth redirect fragment did not contain access_token');
        }

      }

    });
  }
}
