/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import { inject, Injectable } from "@angular/core";
import { HttpClient, HttpContext, HttpEvent, HttpParams, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { ApiResponse, Pet, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";

@Injectable({ providedIn: 'root' })
export class PetService {
  private readonly http = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: import("@angular/common/http").HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  /** Creates a new HttpContext or enhances an existing one with the client identifier token. */
  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request, with response observation enabled.
   */
  uploadFile(petId: number, additionalMetadata: string, file: File | Blob, options: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<ApiResponse>>;
  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request, with event observation enabled.
   */
  uploadFile(petId: number, additionalMetadata: string, file: File | Blob, options: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<ApiResponse>>;
  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request, with a blob response type.
   */
  uploadFile(petId: number, additionalMetadata: string, file: File | Blob, options: RequestOptions & {
    responseType: 'blob'
  }): Observable<Blob>;
  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request, with a text response type.
   */
  uploadFile(petId: number, additionalMetadata: string, file: File | Blob, options: RequestOptions & {
    responseType: 'text'
  }): Observable<string>;
  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request.
   */
  uploadFile(petId: number, additionalMetadata?: string, file?: File | Blob, options?: RequestOptions & {
    observe?: 'body'
  }): Observable<ApiResponse>;
  /** uploads an image */
  uploadFile(petId: number, additionalMetadata?: string, file?: File | Blob, options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}/uploadImage`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    const formData = new FormData();
    if (additionalMetadata != null) {
      formData.append('additionalMetadata', additionalMetadata);
    }
    if (file != null) {
      formData.append('file', file);
    }
    finalOptions.body = formData;
    return this.http.request('post', url, finalOptions);
  }

  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request, with response observation enabled.
   */
  addPet(pet: Pet, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request, with event observation enabled.
   */
  addPet(pet: Pet, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request, with a blob response type.
   */
  addPet(pet: Pet, options: RequestOptions & { responseType: 'blob' }): Observable<Blob>;
  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request, with a text response type.
   */
  addPet(pet: Pet, options: RequestOptions & { responseType: 'text' }): Observable<string>;
  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request.
   */
  addPet(pet?: Pet, options?: RequestOptions & { observe?: 'body' }): Observable<void>;
  /** Add a new pet to the store */
  addPet(pet?: Pet, options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    finalOptions.body = pet;
    return this.http.request('post', url, finalOptions);
  }

  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request, with response observation enabled.
   */
  updatePet(pet: Pet, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request, with event observation enabled.
   */
  updatePet(pet: Pet, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request, with a blob response type.
   */
  updatePet(pet: Pet, options: RequestOptions & { responseType: 'blob' }): Observable<Blob>;
  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request, with a text response type.
   */
  updatePet(pet: Pet, options: RequestOptions & { responseType: 'text' }): Observable<string>;
  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request.
   */
  updatePet(pet?: Pet, options?: RequestOptions & { observe?: 'body' }): Observable<void>;
  /** Update an existing pet */
  updatePet(pet?: Pet, options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    finalOptions.body = pet;
    return this.http.request('put', url, finalOptions);
  }

  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request, with response observation enabled.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<Pet[]>>;
  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request, with event observation enabled.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<Pet[]>>;
  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request, with a blob response type.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options: RequestOptions & {
    responseType: 'blob'
  }): Observable<Blob>;
  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request, with a text response type.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options: RequestOptions & {
    responseType: 'text'
  }): Observable<string>;
  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options?: RequestOptions & {
    observe?: 'body'
  }): Observable<Pet[]>;
  /**
   * Finds Pets by status
   *
   * Multiple status values can be provided with comma separated strings
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet/findByStatus`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    let requestParams = new HttpParams({ fromObject: options?.params as any || {} });
    if (status != null) {
      if (Array.isArray(status)) {
        status.forEach(v => requestParams = requestParams.append('status', String(v)));
      } else {
        requestParams = requestParams.append('status', String(status));
      }
    }
    finalOptions.params = requestParams;
    return this.http.request('get', url, finalOptions);
  }

  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request, with response observation enabled.
   */
  findPetsByTags(tags: string[], options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<Pet[]>>;
  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request, with event observation enabled.
   */
  findPetsByTags(tags: string[], options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<Pet[]>>;
  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request, with a blob response type.
   */
  findPetsByTags(tags: string[], options: RequestOptions & { responseType: 'blob' }): Observable<Blob>;
  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request, with a text response type.
   */
  findPetsByTags(tags: string[], options: RequestOptions & { responseType: 'text' }): Observable<string>;
  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request.
   */
  findPetsByTags(tags: string[], options?: RequestOptions & { observe?: 'body' }): Observable<Pet[]>;
  /**
   * Finds Pets by tags
   *
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   */
  findPetsByTags(tags: string[], options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet/findByTags`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    let requestParams = new HttpParams({ fromObject: options?.params as any || {} });
    if (tags != null) {
      if (Array.isArray(tags)) {
        tags.forEach(v => requestParams = requestParams.append('tags', String(v)));
      } else {
        requestParams = requestParams.append('tags', String(tags));
      }
    }
    finalOptions.params = requestParams;
    return this.http.request('get', url, finalOptions);
  }

  /**
   * getPetById.
   * @param petId
   * @param options The options for this request, with response observation enabled.
   */
  getPetById(petId: number, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<Pet>>;
  /**
   * getPetById.
   * @param petId
   * @param options The options for this request, with event observation enabled.
   */
  getPetById(petId: number, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<Pet>>;
  /**
   * getPetById.
   * @param petId
   * @param options The options for this request, with a blob response type.
   */
  getPetById(petId: number, options: RequestOptions & { responseType: 'blob' }): Observable<Blob>;
  /**
   * getPetById.
   * @param petId
   * @param options The options for this request, with a text response type.
   */
  getPetById(petId: number, options: RequestOptions & { responseType: 'text' }): Observable<string>;
  /**
   * getPetById.
   * @param petId
   * @param options The options for this request.
   */
  getPetById(petId: number, options?: RequestOptions & { observe?: 'body' }): Observable<Pet>;
  /**
   * Find pet by ID
   *
   * Returns a single pet
   */
  getPetById(petId: number, options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    return this.http.request('get', url, finalOptions);
  }

  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request, with response observation enabled.
   */
  updatePetWithForm(petId: number, name: string, status: string, options: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<void>>;
  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request, with event observation enabled.
   */
  updatePetWithForm(petId: number, name: string, status: string, options: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<void>>;
  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request, with a blob response type.
   */
  updatePetWithForm(petId: number, name: string, status: string, options: RequestOptions & {
    responseType: 'blob'
  }): Observable<Blob>;
  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request, with a text response type.
   */
  updatePetWithForm(petId: number, name: string, status: string, options: RequestOptions & {
    responseType: 'text'
  }): Observable<string>;
  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request.
   */
  updatePetWithForm(petId: number, name?: string, status?: string, options?: RequestOptions & {
    observe?: 'body'
  }): Observable<void>;
  /** Updates a pet in the store with form data */
  updatePetWithForm(petId: number, name?: string, status?: string, options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    let formParams = new HttpParams({ fromObject: options?.params as any || {} });
    if (name != null) {
      formParams = formParams.set('name', String(name));
    }
    if (status != null) {
      formParams = formParams.set('status', String(status));
    }
    finalOptions.body = formParams;
    return this.http.request('post', url, finalOptions);
  }

  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request, with response observation enabled.
   */
  deletePet(petId: number, apiKey: string, options: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<void>>;
  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request, with event observation enabled.
   */
  deletePet(petId: number, apiKey: string, options: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<void>>;
  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request, with a blob response type.
   */
  deletePet(petId: number, apiKey: string, options: RequestOptions & { responseType: 'blob' }): Observable<Blob>;
  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request, with a text response type.
   */
  deletePet(petId: number, apiKey: string, options: RequestOptions & { responseType: 'text' }): Observable<string>;
  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request.
   */
  deletePet(petId: number, apiKey?: string, options?: RequestOptions & { observe?: 'body' }): Observable<void>;
  /** Deletes a pet */
  deletePet(petId: number, apiKey?: string, options?: RequestOptions & {
    observe?: "body" | "events" | "response",
    responseType?: "blob" | "text" | "json"
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}`;
    const finalOptions: any = { ...options };
    finalOptions.context = this.createContextWithClientId(options?.context);
    let requestHeaders = options?.headers || {};
    if (apiKey != null) {
      requestHeaders = { ...requestHeaders, ['api_key']: String(apiKey) };
    }
    finalOptions.headers = requestHeaders;
    return this.http.request('delete', url, finalOptions);
  }
}
