/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import { inject, Injectable } from "@angular/core";
import {
  HttpClient,
  HttpContext,
  HttpContextToken,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse
} from "@angular/common/http";
import { Observable } from "rxjs";
import { ApiResponse, Pet, RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";

@Injectable({ providedIn: 'root' })
export class PetService {
  private readonly http = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  /** Creates a new HttpContext or enhances an existing one with the client identifier token. */
  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request.
   */
  uploadFile(petId: number, additionalMetadata?: string, file?: any, options?: RequestOptions & {
    observe?: 'body'
  }): Observable<ApiResponse>;
  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request, with response observation enabled.
   */
  uploadFile(petId: number, additionalMetadata?: string, file?: any, options?: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<ApiResponse>>;
  /**
   * uploadFile.
   * @param petId
   * @param additionalMetadata (optional)
   * @param file (optional)
   * @param options The options for this request, with event observation enabled.
   */
  uploadFile(petId: number, additionalMetadata?: string, file?: any, options?: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<ApiResponse>>;
  /** uploads an image */
  uploadFile(petId: number, additionalMetadata?: string, file?: any, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}/uploadImage`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    const formData = new FormData();
    if (additionalMetadata != null) {
      formData.append('additionalMetadata', additionalMetadata);
    }
    if (file != null) {
      formData.append('file', file);
    }
    return this.http.post(url, formData, requestOptions);
  }

  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request.
   */
  addPet(pet?: Pet, options?: RequestOptions & { observe?: 'body' }): Observable<Pet>;
  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request, with response observation enabled.
   */
  addPet(pet?: Pet, options?: RequestOptions & { observe: 'response' }): Observable<HttpResponse<Pet>>;
  /**
   * addPet.
   * @param pet (optional)
   * @param options The options for this request, with event observation enabled.
   */
  addPet(pet?: Pet, options?: RequestOptions & { observe: 'events' }): Observable<HttpEvent<Pet>>;
  /** Add a new pet to the store */
  addPet(pet?: Pet, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.post(url, pet, requestOptions);
  }

  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request.
   */
  updatePet(pet?: Pet, options?: RequestOptions & { observe?: 'body' }): Observable<Pet>;
  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request, with response observation enabled.
   */
  updatePet(pet?: Pet, options?: RequestOptions & { observe: 'response' }): Observable<HttpResponse<Pet>>;
  /**
   * updatePet.
   * @param pet (optional)
   * @param options The options for this request, with event observation enabled.
   */
  updatePet(pet?: Pet, options?: RequestOptions & { observe: 'events' }): Observable<HttpEvent<Pet>>;
  /** Update an existing pet */
  updatePet(pet?: Pet, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.put(url, pet, requestOptions);
  }

  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options?: RequestOptions & {
    observe?: 'body'
  }): Observable<Pet[]>;
  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request, with response observation enabled.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<Pet[]>>;
  /**
   * findPetsByStatus.
   * @param status
   * @param options The options for this request, with event observation enabled.
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<Pet[]>>;
  /**
   * Finds Pets by status
   *
   * Multiple status values can be provided with comma separated strings
   */
  findPetsByStatus(status: 'available' | 'pending' | 'sold'[], options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet/findByStatus`;
    let params = new HttpParams({ fromObject: options?.params ?? {} });
    if (status != null) {
      params = HttpParamsBuilder.addToHttpParams(params, status, 'status');
    }
    const requestOptions: any = {
      observe: options?.observe,
      params,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.get(url, requestOptions);
  }

  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request.
   */
  findPetsByTags(tags: string[], options?: RequestOptions & { observe?: 'body' }): Observable<Pet[]>;
  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request, with response observation enabled.
   */
  findPetsByTags(tags: string[], options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<Pet[]>>;
  /**
   * findPetsByTags.
   * @param tags
   * @param options The options for this request, with event observation enabled.
   */
  findPetsByTags(tags: string[], options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<Pet[]>>;
  /**
   * Finds Pets by tags
   *
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   */
  findPetsByTags(tags: string[], options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet/findByTags`;
    let params = new HttpParams({ fromObject: options?.params ?? {} });
    if (tags != null) {
      params = HttpParamsBuilder.addToHttpParams(params, tags, 'tags');
    }
    const requestOptions: any = {
      observe: options?.observe,
      params,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.get(url, requestOptions);
  }

  /**
   * getPetById.
   * @param petId
   * @param options The options for this request.
   */
  getPetById(petId: number, options?: RequestOptions & { observe?: 'body' }): Observable<Pet>;
  /**
   * getPetById.
   * @param petId
   * @param options The options for this request, with response observation enabled.
   */
  getPetById(petId: number, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<Pet>>;
  /**
   * getPetById.
   * @param petId
   * @param options The options for this request, with event observation enabled.
   */
  getPetById(petId: number, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<Pet>>;
  /**
   * Find pet by ID
   *
   * Returns a single pet
   */
  getPetById(petId: number, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.get(url, requestOptions);
  }

  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request.
   */
  updatePetWithForm(petId: number, name?: string, status?: string, options?: RequestOptions & {
    observe?: 'body'
  }): Observable<any>;
  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request, with response observation enabled.
   */
  updatePetWithForm(petId: number, name?: string, status?: string, options?: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<any>>;
  /**
   * updatePetWithForm.
   * @param petId
   * @param name (optional)
   * @param status (optional)
   * @param options The options for this request, with event observation enabled.
   */
  updatePetWithForm(petId: number, name?: string, status?: string, options?: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<any>>;
  /** Updates a pet in the store with form data */
  updatePetWithForm(petId: number, name?: string, status?: string, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    let formBody = new HttpParams();
    if (name != null) {
      formBody = formBody.append('name', name);
    }
    if (status != null) {
      formBody = formBody.append('status', status);
    }
    return this.http.post(url, formBody, requestOptions);
  }

  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request.
   */
  deletePet(petId: number, apiKey?: string, options?: RequestOptions & { observe?: 'body' }): Observable<any>;
  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request, with response observation enabled.
   */
  deletePet(petId: number, apiKey?: string, options?: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<any>>;
  /**
   * deletePet.
   * @param petId
   * @param apiKey (optional)
   * @param options The options for this request, with event observation enabled.
   */
  deletePet(petId: number, apiKey?: string, options?: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<any>>;
  /** Deletes a pet */
  deletePet(petId: number, apiKey?: string, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/pet/${petId}`;
    let headers = options?.headers instanceof HttpHeaders ? options.headers : new HttpHeaders(options?.headers ?? {});
    if (apiKey != null) {
      headers = headers.set('api_key', String(apiKey));
    }
    const requestOptions: any = {
      observe: options?.observe,
      headers,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.delete(url, requestOptions);
  }
}
