/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
import { Injectable, inject } from "@angular/core";
import { HttpClient, HttpContext, HttpParams, HttpResponse, HttpEvent, HttpHeaders, HttpContextToken } from "@angular/common/http";
import { Observable } from "rxjs";
import type { RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { Order } from "../models/index";

@Injectable({ providedIn: 'root' })
export class StoreService {
    private readonly http = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    /** Creates a new HttpContext with the client identifier token. */
    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getInventory(options?: RequestOptions): Observable<any>;
    getInventory(options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<any>>;
    getInventory(options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<any>>;
    getInventory(options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/store/inventory`;

        return this.http.get<any>(url, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    placeOrder(body: Order, options?: RequestOptions): Observable<any>;
    placeOrder(body: Order, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<any>>;
    placeOrder(body: Order, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<any>>;
    placeOrder(body: Order, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/store/order`;

        return this.http.post<any>(url, body, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    getOrderById(orderId: any, options?: RequestOptions): Observable<any>;
    getOrderById(orderId: any, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<any>>;
    getOrderById(orderId: any, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<any>>;
    getOrderById(orderId: any, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/store/order/${orderId}`;

        return this.http.get<any>(url, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    deleteOrder(orderId: any, options?: RequestOptions): Observable<void>;
    deleteOrder(orderId: any, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
    deleteOrder(orderId: any, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
    deleteOrder(orderId: any, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/store/order/${orderId}`;

        return this.http.delete<void>(url, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }
}
