/**
 * This file is generated by a tool. Do not edit directly.
 * Generated by openapi-angular-generator.
 */
import { inject, Injectable } from "@angular/core";
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpParams, HttpResponse } from "@angular/common/http";
import { Observable } from "rxjs";
import { RequestOptions, User } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";

@Injectable({ providedIn: 'root' })
export class UserService {
  private readonly http = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  /** Creates a new HttpContext or enhances an existing one with the client identifier token. */
  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  /**
   * createUsersWithListInput.
   * @param user (optional)
   * @param options The options for this request.
   */
  createUsersWithListInput(user?: User[], options?: RequestOptions & { observe?: 'body' }): Observable<User[]>;
  /**
   * createUsersWithListInput.
   * @param user (optional)
   * @param options The options for this request, with response observation enabled.
   */
  createUsersWithListInput(user?: User[], options?: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<User[]>>;
  /**
   * createUsersWithListInput.
   * @param user (optional)
   * @param options The options for this request, with event observation enabled.
   */
  createUsersWithListInput(user?: User[], options?: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<User[]>>;
  /** Creates list of users with given input array */
  createUsersWithListInput(user?: User[], options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user/createWithList`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.post(url, user, requestOptions);
  }

  /**
   * getUserByName.
   * @param username
   * @param options The options for this request.
   */
  getUserByName(username: string, options?: RequestOptions & { observe?: 'body' }): Observable<User>;
  /**
   * getUserByName.
   * @param username
   * @param options The options for this request, with response observation enabled.
   */
  getUserByName(username: string, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<User>>;
  /**
   * getUserByName.
   * @param username
   * @param options The options for this request, with event observation enabled.
   */
  getUserByName(username: string, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<User>>;
  /** Get user by user name */
  getUserByName(username: string, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user/${username}`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.get(url, requestOptions);
  }

  /**
   * updateUser.
   * @param username
   * @param user (optional)
   * @param options The options for this request.
   */
  updateUser(username: string, user?: User, options?: RequestOptions & { observe?: 'body' }): Observable<User>;
  /**
   * updateUser.
   * @param username
   * @param user (optional)
   * @param options The options for this request, with response observation enabled.
   */
  updateUser(username: string, user?: User, options?: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<User>>;
  /**
   * updateUser.
   * @param username
   * @param user (optional)
   * @param options The options for this request, with event observation enabled.
   */
  updateUser(username: string, user?: User, options?: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<User>>;
  /**
   * Updated user
   *
   * This can only be done by the logged in user.
   */
  updateUser(username: string, user?: User, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user/${username}`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.put(url, user, requestOptions);
  }

  /**
   * deleteUser.
   * @param username
   * @param options The options for this request.
   */
  deleteUser(username: string, options?: RequestOptions & { observe?: 'body' }): Observable<any>;
  /**
   * deleteUser.
   * @param username
   * @param options The options for this request, with response observation enabled.
   */
  deleteUser(username: string, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<any>>;
  /**
   * deleteUser.
   * @param username
   * @param options The options for this request, with event observation enabled.
   */
  deleteUser(username: string, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<any>>;
  /**
   * Delete user
   *
   * This can only be done by the logged in user.
   */
  deleteUser(username: string, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user/${username}`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.delete(url, requestOptions);
  }

  /**
   * loginUser.
   * @param username
   * @param password
   * @param options The options for this request.
   */
  loginUser(username: string, password: string, options?: RequestOptions & { observe?: 'body' }): Observable<string>;
  /**
   * loginUser.
   * @param username
   * @param password
   * @param options The options for this request, with response observation enabled.
   */
  loginUser(username: string, password: string, options: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<string>>;
  /**
   * loginUser.
   * @param username
   * @param password
   * @param options The options for this request, with event observation enabled.
   */
  loginUser(username: string, password: string, options: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<string>>;
  /** Logs user into the system */
  loginUser(username: string, password: string, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user/login`;
    let params = new HttpParams({ fromObject: options?.params ?? {} });
    if (username != null) {
      params = HttpParamsBuilder.addToHttpParams(params, username, 'username');
    }
    if (password != null) {
      params = HttpParamsBuilder.addToHttpParams(params, password, 'password');
    }
    const requestOptions: any = {
      observe: options?.observe,
      params,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.get(url, requestOptions);
  }

  /**
   * logoutUser.
   *
   * @param options The options for this request.
   */
  logoutUser(options?: RequestOptions & { observe?: 'body' }): Observable<any>;
  /**
   * logoutUser.
   *
   * @param options The options for this request, with response observation enabled.
   */
  logoutUser(options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<any>>;
  /**
   * logoutUser.
   *
   * @param options The options for this request, with event observation enabled.
   */
  logoutUser(options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<any>>;
  /** Logs out current logged in user session */
  logoutUser(options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user/logout`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.get(url, requestOptions);
  }

  /**
   * createUsersWithArrayInput.
   * @param user (optional)
   * @param options The options for this request.
   */
  createUsersWithArrayInput(user?: User[], options?: RequestOptions & { observe?: 'body' }): Observable<User[]>;
  /**
   * createUsersWithArrayInput.
   * @param user (optional)
   * @param options The options for this request, with response observation enabled.
   */
  createUsersWithArrayInput(user?: User[], options?: RequestOptions & {
    observe: 'response'
  }): Observable<HttpResponse<User[]>>;
  /**
   * createUsersWithArrayInput.
   * @param user (optional)
   * @param options The options for this request, with event observation enabled.
   */
  createUsersWithArrayInput(user?: User[], options?: RequestOptions & {
    observe: 'events'
  }): Observable<HttpEvent<User[]>>;
  /** Creates list of users with given input array */
  createUsersWithArrayInput(user?: User[], options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user/createWithArray`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.post(url, user, requestOptions);
  }

  /**
   * createUser.
   * @param user (optional)
   * @param options The options for this request.
   */
  createUser(user?: User, options?: RequestOptions & { observe?: 'body' }): Observable<User>;
  /**
   * createUser.
   * @param user (optional)
   * @param options The options for this request, with response observation enabled.
   */
  createUser(user?: User, options?: RequestOptions & { observe: 'response' }): Observable<HttpResponse<User>>;
  /**
   * createUser.
   * @param user (optional)
   * @param options The options for this request, with event observation enabled.
   */
  createUser(user?: User, options?: RequestOptions & { observe: 'events' }): Observable<HttpEvent<User>>;
  /**
   * Create user
   *
   * This can only be done by the logged in user.
   */
  createUser(user?: User, options?: RequestOptions & {
    observe?: 'body' | 'events' | 'response',
    responseType?: 'arraybuffer' | 'blob' | 'json' | 'text'
  }): Observable<any> {
    const url = `${this.basePath}/user`;
    const requestOptions: any = {
      observe: options?.observe,
      reportProgress: options?.reportProgress,
      responseType: options?.responseType,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context)
    };
    return this.http.post(url, user, requestOptions);
  }
}
