/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
import { Injectable, inject } from "@angular/core";
import { HttpClient, HttpContext, HttpParams, HttpResponse, HttpEvent, HttpHeaders, HttpContextToken } from "@angular/common/http";
import { Observable } from "rxjs";
import type { RequestOptions } from "../models";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { User } from "../models/index";

@Injectable({ providedIn: 'root' })
export class UserService {
    private readonly http = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    /** Creates a new HttpContext with the client identifier token. */
    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    createUsersWithListInput(body: User[], options?: RequestOptions): Observable<void>;
    createUsersWithListInput(body: User[], options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
    createUsersWithListInput(body: User[], options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
    createUsersWithListInput(body: User[], options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user/createWithList`;

        return this.http.post<void>(url, body, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    getUserByName(username: any, options?: RequestOptions): Observable<any>;
    getUserByName(username: any, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<any>>;
    getUserByName(username: any, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<any>>;
    getUserByName(username: any, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user/${username}`;

        return this.http.get<any>(url, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    updateUser(username: any, body: User, options?: RequestOptions): Observable<void>;
    updateUser(username: any, body: User, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
    updateUser(username: any, body: User, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
    updateUser(username: any, body: User, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user/${username}`;

        return this.http.put<void>(url, body, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    deleteUser(username: any, options?: RequestOptions): Observable<void>;
    deleteUser(username: any, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
    deleteUser(username: any, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
    deleteUser(username: any, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user/${username}`;

        return this.http.delete<void>(url, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    loginUser(username: any, password: any, options?: RequestOptions): Observable<any>;
    loginUser(username: any, password: any, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<any>>;
    loginUser(username: any, password: any, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<any>>;
    loginUser(username: any, password: any, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user/login`;

        let params = new HttpParams();
        if (username != null) params = HttpParamsBuilder.addToHttpParams(params, username, 'username');
        if (password != null) params = HttpParamsBuilder.addToHttpParams(params, password, 'password');

        return this.http.get<any>(url, { ...options, context: this.createContextWithClientId(options?.context), params } as any);
    }

    logoutUser(options?: RequestOptions): Observable<void>;
    logoutUser(options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
    logoutUser(options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
    logoutUser(options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user/logout`;

        return this.http.get<void>(url, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    createUsersWithArrayInput(body: User[], options?: RequestOptions): Observable<void>;
    createUsersWithArrayInput(body: User[], options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
    createUsersWithArrayInput(body: User[], options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
    createUsersWithArrayInput(body: User[], options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user/createWithArray`;

        return this.http.post<void>(url, body, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }

    createUser(body: User, options?: RequestOptions): Observable<void>;
    createUser(body: User, options: RequestOptions & { observe: 'response' }): Observable<HttpResponse<void>>;
    createUser(body: User, options: RequestOptions & { observe: 'events' }): Observable<HttpEvent<void>>;
    createUser(body: User, options?: RequestOptions & { observe?: 'body' | 'response' | 'events' }): Observable<any> {
        const url = `${this.basePath}/user`;

        return this.http.post<void>(url, body, { ...options, context: this.createContextWithClientId(options?.context) } as any);
    }
}
