/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for User controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpParams } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT, RequestOptions } from "../";
import { HttpParamsBuilder } from "../utils";
import { User } from "../models";

@Injectable({ providedIn: "root" })
export class UserService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    public(params: Params, options?: RequestOptions): Observable<void> {
        const url = `${this.basePath}/user/createWithList`;
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.POST<void>(url, null, { context });
    }

    public undefined2(params: Undefined2Params, options?: RequestOptions): Observable<User> {
        const url = `${this.basePath}/user/${params.username}`;
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.GET<User>(url, null, { context });
    }

    public undefined3(params: Undefined3Params, options?: RequestOptions): Observable<void> {
        const url = `${this.basePath}/user/${params.username}`;
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.PUT<void>(url, null, { context });
    }

    public undefined4(params: Undefined4Params, options?: RequestOptions): Observable<void> {
        const url = `${this.basePath}/user/${params.username}`;
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.DELETE<void>(url, null, { context });
    }

    public undefined5(params: Undefined5Params, options?: RequestOptions): Observable<string> {
        const url = `${this.basePath}/user/login`;
        const paramsBuilder = new HttpParamsBuilder();
        paramsBuilder.append('username', params.username);
        paramsBuilder.append('password', params.password);
        const httpParams = paramsBuilder.build();
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.GET<string>(url, null, { params: httpParams, context });
    }

    public undefined6(options?: RequestOptions): Observable<void> {
        const url = `${this.basePath}/user/logout`;
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.GET<void>(url, null, { context });
    }

    public undefined7(params: Undefined7Params, options?: RequestOptions): Observable<void> {
        const url = `${this.basePath}/user/createWithArray`;
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.POST<void>(url, null, { context });
    }

    public undefined8(params: Undefined8Params, options?: RequestOptions): Observable<void> {
        const url = `${this.basePath}/user`;
        const context = this.createContextWithClientId(options?.context);
        return this.httpClient.POST<void>(url, null, { context });
    }
}

export interface Params {
    body: User[];
}

export interface Undefined2Params {
    username: string;
}

export interface Undefined3Params {
    username: string;
    body: User;
}

export interface Undefined4Params {
    username: string;
}

export interface Undefined5Params {
    username: string;
    password: string;
}

export interface Undefined7Params {
    body: User[];
}

export interface Undefined8Params {
    body: User;
}
