/**
* This file is generated by a tool. Do not edit directly.
* Generated by openapi-angular-generator.
*/
import { InjectionToken } from "@angular/core";
import { HttpInterceptor, HttpContextToken } from "@angular/common/http";

/** Injection token for providing the base API path for the 'default' client. */
export const BASE_PATH_DEFAULT = new InjectionToken<string>('BASE_PATH_DEFAULT');
/** Injection token for providing an array of client-specific HttpInterceptor instances */
/** for the 'default' client. */
export const HTTP_INTERCEPTORS_DEFAULT = new InjectionToken<HttpInterceptor[]>('HTTP_INTERCEPTORS_DEFAULT', {
    providedIn: 'root',
    factory: () => [], // Default to an empty array if not provided
});
/** HttpContextToken used to identify which requests belong to the 'default' client. */
/** This allows the BaseInterceptor to apply the correct set of interceptors. */
export const CLIENT_CONTEXT_TOKEN_DEFAULT = new HttpContextToken<string>(() => 'default');
